FROM nvidia/cuda:12.4.1-cudnn-devel-ubuntu22.04

WORKDIR /workdir

RUN rm -rf /workdir/deforum

COPY sources/deforum-studio ./deforum

RUN apt-get update && \
    apt-get install -y git python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workdir/deforum

RUN pip install -e .[dev]

RUN git clone https://github.com/comfyanonymous/ComfyUI.git /workdir/deforum/src/ComfyUI
WORKDIR /workdir/deforum/src/ComfyUI
RUN git checkout daa92a8ff4d3e75a3b17bb1a6b6c508b27264ff5

WORKDIR /workdir/deforum
